# Site settings
title: golden-garage.net
email: golden@golden-garage.net
description: > # this means to ignore newlines until "baseurl:"
  This garage incubates the future.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://golden-garage.net" # the base hostname & protocol for your site
github_username:  golden-garage

# Build settings
markdown: kramdown
